"""Build a class-balance table from all experiment metrics.json files.

For each experiment the script reads every fold's confusion matrix, sums the
true low/high counts across folds, and reports the overall class distribution.
It also extracts the median label threshold used by the labeler.

Outputs:
    results/class_balance.md
    results/class_balance.csv

Usage:
    python scripts/build_class_balance_table.py
"""
import csv
import json
from pathlib import Path

RESULTS_DIR = Path("results")
OUTPUT_MD = RESULTS_DIR / "class_balance.md"
OUTPUT_CSV = RESULTS_DIR / "class_balance.csv"


def load_metrics(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def sum_confusion_matrices(fold_results):
    """Sum confusion matrices across folds.

    Layout: [[TN_low_as_low, FP_high_as_low], [FN_low_as_high, TP_high_as_high]]
    True low = TN + FN, True high = FP + TP.
    """
    total_low = 0
    total_high = 0
    for fold in fold_results:
        cm = fold.get("confusion_matrix")
        if not cm or len(cm) != 2 or len(cm[0]) != 2 or len(cm[1]) != 2:
            continue
        tn, fp = cm[0]
        fn, tp = cm[1]
        total_low += tn + fn
        total_high += fp + tp
    return total_low, total_high


def build_table():
    rows = []
    for metrics_file in sorted(RESULTS_DIR.rglob("metrics.json")):
        experiment = metrics_file.parent.name
        metrics = load_metrics(metrics_file)
        if metrics is None:
            continue
        labeler = metrics.get("labeler_description", {})
        models = metrics.get("models", {})
        if not models:
            continue
        # Use the first model's fold results (all models share the same folds)
        first_model = next(iter(models.values()))
        fold_results = first_model.get("fold_results", [])
        if not fold_results:
            continue
        low, high = sum_confusion_matrices(fold_results)
        total = low + high
        rows.append({
            "experiment": experiment,
            "median": labeler.get("median"),
            "low_threshold": labeler.get("low_threshold"),
            "high_threshold": labeler.get("high_threshold"),
            "low": low,
            "high": high,
            "total": total,
            "low_pct": (low / total * 100) if total else 0.0,
            "high_pct": (high / total * 100) if total else 0.0,
        })
    return rows


def format_value(v, decimals=3):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.{decimals}f}"
    return str(v)


def write_md(rows):
    lines = [
        "# Class Balance per Experiment",
        "",
        "True class distribution across all LOSO folds. Labels are generated by median split.",
        "",
        "| Experiment | Median | Low n | High n | Total | Low % | High % | Balance |",
    ]
    lines.append("|------------|--------|-------|--------|-------|-------|--------|---------|")
    for row in rows:
        pct_diff = abs(row["low_pct"] - row["high_pct"])
        if pct_diff <= 5:
            balance = "balanced"
        elif pct_diff <= 15:
            balance = "slight imbalance"
        elif row["low_pct"] > row["high_pct"]:
            balance = "low majority"
        else:
            balance = "high majority"
        lines.append(
            f"| {row['experiment']} | {format_value(row['median'])} | "
            f"{row['low']} | {row['high']} | {row['total']} | "
            f"{format_value(row['low_pct'], 1)} | {format_value(row['high_pct'], 1)} | {balance} |"
        )
    lines.append("")
    lines.append("*Generated from confusion matrices in results/<experiment>/metrics.json.*")
    OUTPUT_MD.write_text("\n".join(lines), encoding="utf-8")


def write_csv(rows):
    fieldnames = [
        "experiment", "median", "low_threshold", "high_threshold",
        "low", "high", "total", "low_pct", "high_pct",
    ]
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: (row[k] if row[k] is not None else "") for k in fieldnames})


if __name__ == "__main__":
    rows = build_table()
    if not rows:
        print("No metrics found.")
    else:
        write_md(rows)
        write_csv(rows)
        print(f"Wrote {OUTPUT_MD}")
        print(f"Wrote {OUTPUT_CSV}")
